### PR TITLE
A few things to add/change

### PR DESCRIPTION
**Pull request by randomzigzag**
* Unregister `decode` command when unloading
* Remove unecessary extra functions
* Don't send the message to the channel
* Include original message + wrap base64 in mini-codeblock

### CODE REVIEW

**Comment by randomzigzag** [comment]
Example:

DiscordCanary_bvL2HI60FN

**Comment by adntaha** [comment]
You should add a `--send` option to directly send the message in chat

**Comment by dutake** [comment]
> 
> 
> You should add a `--send` option to directly send the message in chat

Alr I can go work on that

**Comment by dutake** [comment]
> 
> 
> > You should add a `--send` option to directly send the message in chat
> 
> Alr I can go work on that

Actually i feel like from a user perspective it'd be easier for them to copy & send it rather than do --send, right?

**Comment by randomzigzag** [comment]
~~I started working on `--send` after I saw botato's comment, should I let you do it?~~ #2.

**Pull request merged**
